name: Create Release Artifact

on:
  push:
    tags:
      - 'v*.*.*_(snapd_v*.*.*)'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.5'

    - name: Extract versions from tag
      id: extract_versions
      run: |
        TAG_NAME=${GITHUB_REF##*/}
        UBUNTU_IMAGE_VERSION=$(echo $TAG_NAME | cut -d'_' -f1)
        SNAPD_VERSION=$(echo $TAG_NAME | sed -n 's/^.*(snapd_v\([0-9.]*\)).*$/\1/p')
        echo "UBUNTU_IMAGE_VERSION=$UBUNTU_IMAGE_VERSION" >> $GITHUB_ENV
        echo "SNAPD_VERSION=$SNAPD_VERSION" >> $GITHUB_ENV

    - name: Download snapd tarball
      run: |
        SNAPD_URL=https://github.com/ML-PA-Consulting-GmbH/snapd/releases/download/v${{ env.SNAPD_VERSION }}/snapd_v${{ env.SNAPD_VERSION }}.tar
        curl -L $SNAPD_URL -o /tmp/snapd_v${{ env.SNAPD_VERSION }}.tar

    - name: Untar snapd
      run: |
        mkdir -p /tmp/snapd
        tar -xf /tmp/snapd_v${{ env.SNAPD_VERSION }}.tar -C /tmp/snapd
        ls -la /tmp/snapd

    - name: Pull dependencies and update go.mod
      run: |
        go mod edit -replace github.com/snapcore/snapd=/tmp/snapd
        go mod tidy
        go mod vendor

    - name: Create tarball
      run: |
        tar cfah /tmp/ubuntu-image_${{ env.UBUNTU_IMAGE_VERSION }}.tar .

    - name: Get release ID
      id: get_release
      run: |
        TAG_NAME=${GITHUB_REF##*/}
        RELEASE_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/tags/$TAG_NAME" | jq -r .id)
        echo "RELEASE_ID=${RELEASE_ID}" >> $GITHUB_ENV
        echo "Tag name: $TAG_NAME"
        echo "Release ID: $RELEASE_ID"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ env.RELEASE_ID }}/assets?name=ubuntu-image_${{ env.UBUNTU_IMAGE_VERSION }}.tar"
        asset_path: /tmp/ubuntu-image_${{ env.UBUNTU_IMAGE_VERSION }}.tar
        asset_name: ubuntu-image_${{ env.UBUNTU_IMAGE_VERSION }}.tar
        asset_content_type: application/x-tar
